### ISSUE TITLE
Fix tests and badges like CI, code coverage, etc.

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/postgresql-watcher#4]
![image](https://user-images.githubusercontent.com/3787410/113536740-5fbc9a80-9609-11eb-9256-67ad7d59d04b.png)

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
working on this

**Comment by Zxilly** [comment]
@hsluoyz seems this project is still under development. CI will not include automatic release.

**Comment by hsluoyz** [comment]
@ashish493

**Comment by ashish493** [comment]
Will start working on it.

**Comment by ashish493** [comment]
@hsluoyz , 
In the [line](https://github.com/pycasbin/postgresql-watcher/blob/cfef96c3aa0a242595ac8dcb2be5f0f9c594b0f3/postgresql_watcher/watcher.py#L11) mentioned in the function of casbin_subscription, I couldn't find any type of attribute related to multiprocessing.connection.pipeconnection.  I even tried seaching on official [docs](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.connection) but couldn't find it. And if there isn't any such attribute, then rectifying it would be hard. :(

Also the postgreSQL [action](https://github.com/pycasbin/postgresql-watcher/blob/cfef96c3aa0a242595ac8dcb2be5f0f9c594b0f3/.github/workflows/release.yml#L27) used in the CI only works for Linux. For mac and windows, I need to setup the postgreSQL manually for the CI.

**Comment by hsluoyz** [comment]
@Zxilly any comment?

**Comment by Zxilly** [comment]
@ashish493 plz turn to @LiuG-lynx for help.
Maybe there's no need to test watcher on different platform? If you do want to test it on MacOS or Windows, you need to manually setup database.

**Comment by hsluoyz** [comment]
@Zxilly 

I guess @LiuG-lynx is not in the community any more. We need to resolve it by ourselves.

I don't think we need to run tests all so many OSs. Only testing against Linux is OK. But we need to just make sure the final code can run on all OSs, for example, don't use a Windows-specific API to make it fail to run on Linux.

**Comment by Zxilly** [comment]
@hsluoyz I'm working on cross platform support.

**Comment by hsluoyz** [comment]
@Zxilly CI is fixed, thanks!

Coverage is still down.

![image](https://user-images.githubusercontent.com/3787410/118846678-8c99e800-b8ff-11eb-9984-2da8ac6a7e9b.png)

**Comment by Zxilly** [comment]
@hsluoyz I will add it to CI.

**Comment by hsluoyz** [comment]
Done:

![image](https://user-images.githubusercontent.com/3787410/123352158-4f291a00-d591-11eb-9f31-fcccf32b4ed4.png)
